#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
#######################################################################
#
# Copyright © 2018 Jim Lee <jlee54@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################
#
#  ltv-log
#
#  A leetv utility program
#
#  Print today's log file from leetv,
#  either from the local machine or
#  a remotely mounted machine (default).
#
#  Last update: 2018-05-28
#
import sys
import os
import argparse
import urllib.parse
from datetime import date, datetime

from leeutils import Log


def main(local):

    # create a LOG object
    log = Log(level='INFO')

    # look at local machine log or remote machine log
    if local:
        directory = os.path.join(os.getenv('HOME'), '.leetv', 'log')
    else:
        # "HOME" directory of remote machine mounted at /mnt/leetv
        directory = os.path.abspath(os.path.join(os.sep, 'mnt', 'leetv', '.leetv', 'log'))

    today = date.strftime(date.today(), '%Y%m%d')
    file = os.path.join(directory, today + '.log')

    if os.path.isfile(file):
        with open(file, 'r') as fp:
            for x in fp.readlines():
                print(x, end='')
    else:
        log.error("Log file {} does not exist.".format(file))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Show today's leetv log")
    parser.add_argument("-l", "--local", action="store_true", help="print local machine log")
    args = parser.parse_args()
    local = args.local
    sys.exit(main(local))
