#!/bin/sh
#######################################################################
#
# Copyright © 2018 Jim Lee
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################
#
#  normalize
#
#  A leetv utility program
#
#  Normalize the audio for a set of videos files.
#  Especially useful for commercials obtained from
#  diverse sources.
#
#  Last update: 2018-05-28
#
ffmpeg-normalize *.mp4 -c:a aac -b:a 192k -ext mp4 -v
#ffmpeg-normalize *.avi -ext avi -v
#find . -name "*.avi" -exec ffmpeg -i {} -vf normalize=blackpt=black:whitept=white:smoothing=50 -vf eq=gamma_g=0.7 ~/tmp/`basename {}`.mp4 \;
